kind: Deployment
apiVersion: apps/v1
metadata:
  name: react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react
          image: react
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always