kind: Service
apiVersion: v1
metadata:
  name: react
  namespace: default
spec:
  externalTrafficPolicy: Local
  ports:
     -name: http 
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: react
  type:Nodeport